version: "3.8"

x-restart-policy: &restart-policy unless-stopped
x-logging-policy:
  &logging-policy
  options:
    max-file: "5"
    max-size: "20m"

services:
  postgres:
    image: postgres:${POSTGRES_TAG}
    restart: *restart-policy
    logging: *logging-policy
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./${COMPOSE_ROOT_DIR}/db/init:/docker-entrypoint-initdb.d:z
      - ./${COMPOSE_ROOT_DIR}/db/data:/var/lib/postgresql/data:Z
