# https://github.com/nextcloud/docker
# https://hub.docker.com/_/nextcloud/tags
version: "3.8"

x-restart-policy: &restart-policy unless-stopped
x-logging-policy:
  &logging-policy
  options:
    max-file: "5"
    max-size: "20m"

# services
services:
  nextcloud:
    image: nextcloud:${NEXTCLOUD_TAG}
    restart: *restart-policy
    logging: *logging-policy
    ports:
      - 8070:80
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
    volumes:
      - ./${COMPOSE_ROOT_DIR}/nextcloud:/var/www/html

  postgres:
    image: postgres:${POSTGRES_TAG}
    restart: *restart-policy
    logging: *logging-policy
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./${COMPOSE_ROOT_DIR}/db/init:/docker-entrypoint-initdb.d:z
      - ./${COMPOSE_ROOT_DIR}/db/data:/var/lib/postgresql/data:Z
