FROM python:3.8

# RUN mkdir /mlflow/

RUN pip install mlflow~=1.20.2 boto3~=1.18.56 psycopg2-binary~=2.9.1

# RUN apt update && apt install -y sqlite3 libsqlite3-dev
# RUN /usr/bin/sqlite3 /mlflow.db
