version: '3.8'

x-restart-policy: &restart-policy
  restart: unless-stopped

x-logging-policy: &logging-policy
  logging:
    options:
      max-file: "5"
      max-size: "20m"


services:
  minio:
    image: minio/minio:RELEASE.2021-10-02T16-31-05Z
    <<: *restart-policy
    <<: *logging-policy
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
    ports:
      - 9000:9000
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio
    command: server /data

  postgresql:
    image: postgres:14.0-alpine
    <<: *restart-policy
    <<: *logging-policy
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - db:/var/lib/pgsql

  mlflow:
    build: .
    <<: *restart-policy
    <<: *logging-policy
    environment:
      - AWS_ACCESS_KEY_ID=${MINIO_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${MINIO_SECRET_KEY}
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
    ports:
      - 5000:5000
    volumes:
      - mlflow/data:/mlflow
    depends_on:
      - minio
      - postgresql
    command: >
      mlflow server
        --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql/${POSTGRES_DB}
        --default-artifact-root s3://mlflow/artifacts
        --host 0.0.0.0

volumes:
  db:
    driver_opts:
      type: none
      device: ${PWD}/db
      o: bind
  mlflow:
    driver_opts:
      type: none
      device: ${PWD}/mlflow
      o: bind

# Don`t forget to create mlflow bucket!
