version: '3.8'

x-restart-policy: &restart-policy
  restart: unless-stopped

x-logging-policy: &logging-policy
  logging:
    options:
      max-file: "5"
      max-size: "20m"


services:
  minio:
    image: minio/minio:RELEASE.2021-10-02T16-31-05Z
    <<: *restart-policy
    <<: *logging-policy
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
    ports:
      - ${MINIO_API_EXT_PORT}:9000
      - ${MINIO_CONSOLE_EXT_PORT}:9001
    volumes:
      - minio_data:/data
      # - ./minio/config:/root/.minio
    command: server /data --console-address :9001

  postgresql:
    image: postgres:14.0-alpine
    <<: *restart-policy
    <<: *logging-policy
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - PGDATA=/var/lib/pgsql
    volumes:
      - db:/var/lib/pgsql

  mlflow:
    build: .
    <<: *restart-policy
    <<: *logging-policy
    environment:
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
    ports:
      - ${MLFLOW_EXT_PORT}:5000
    volumes:
      - mlflow:/mlflow
    depends_on:
      - minio
      - postgresql
    command: >
      mlflow server
        --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql/${POSTGRES_DB}
        --default-artifact-root s3://mlflow/artifacts
        --host 0.0.0.0

volumes:
  minio_data:
    driver_opts:
      type: none
      device: $PWD/volumes/minio/data
      o: bind
  db:
    driver_opts:
      type: none
      device: $PWD/volumes/db
      o: bind
  mlflow:
    driver_opts:
      type: none
      device: $PWD/volumes/mlflow
      o: bind
