version: "3.6"

x-restart-policy: &restart-policy
  restart: unless-stopped

x-logging-policy: &logging-policy
  logging:
    options:
      max-file: "5"
      max-size: "20m"


volumes:
  minio_data:
    driver_opts:
      type: none
      device: $PWD/data
      o: bind

services:
  minio:
    image: minio/minio:RELEASE.2022-12-12T19-27-27Z
    command: server --console-address ":9001" /data
    <<: *restart-policy
    <<: *logging-policy
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3