version: "3.8"

x-restart-policy: &restart-policy unless-stopped
x-logging-policy:
  &logging-policy
  options:
    max-file: "5"
    max-size: "20m"

services:
  spark:
    image: docker.io/bitnami/spark:${SPARK_TAG}
    restart: *restart-policy
    logging: *logging-policy
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - 8080:8080

  spark-worker:
    image: docker.io/bitnami/spark:${SPARK_TAG}
    restart: *restart-policy
    logging: *logging-policy
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=${SPARK_WORKER_MEMORY}
      - SPARK_WORKER_CORES=${SPARK_WORKER_CORES}
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      