FROM nvidia/cuda:11.3.0-cudnn8-runtime-ubuntu20.04

RUN apt-get update \
    && apt-get dist-upgrade -y \
    && apt-get install -y curl python3-pip git
    
RUN python3 -m pip install --upgrade pip \
    && python3 -m pip install "poetry~=1.3.0"
